version: "3"
services:
  backend:
    build: ./backend
    container_name: 'backend-airports'
    command: sh -c 'npm install; npm run start'
    ports:
      - 3000:3000
    environment:
      - MONGODB_HOST=mongodb-airports
      - MONGODB_PORT=27017
    volumes:
      - /home/thomas/Escritorio/Bases de Datos NSQL/tp5-Airports/backend:/backend
    depends_on:
      - mongodb-airports

  mongodb-airports:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017

  frontend:
    build: ./frontend
    container_name: 'frontend-tp5'
    command: sh -c 'npm install; npm run dev -- --host'
    ports:
      - 5173:5173
    volumes:
      - /home/thomas/Escritorio/Bases de Datos NSQL/tp5-Airports/frontend:/frontend
    depends_on:
      - backend
    stdin_open: true
    tty: true