version: "3"
services:
  backend:
    build: ./back-tp2
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - /home/thomas/Escritorio/Bases de Datos NSQL/tp2-redis/back-tp2:/back-tp2
    depends_on:
      - "db-redis-node"
  db-redis-node:
    container_name: 'redis-backend'
    image: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./front-tp2
    container_name: 'redis_frontend'
    image: node:16.20.0-alpine3.16
    command: sh -c 'npm install; npm run dev'
    volumes:
      - /home/thomas/Escritorio/Bases de Datos NSQL/tp-personajes-redis/front-tp2:/front-tp2
    depends_on:
      - "backend"
    stdin_open: true
    tty: true